# Generated by Django 4.0.3 on 2022-03-15 11:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('abstract', models.TextField(null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('publish_date', models.DateTimeField()),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
